### PR TITLE
Fix depwarn and test failure on 0.5

### PR DESCRIPTION
**Pull request by yuyichao**
symbol ASCIIString, and UTF8String

Requires Compat 0.7.16 to fix depwarn on 0.5 (for the string types) but only require 0.7.15 (for symbol) to work.

### CODE REVIEW

**Comment by yuyichao** [comment]
@staticfloat

**Comment by staticfloat** [comment]
Where can I read about the new `String` changes?

**Comment by yuyichao** [comment]
Summary issue https://github.com/JuliaLang/julia/issues/16107

**Comment by yuyichao** [comment]
The build failure on windows with julia 0.3 doesn't seem to be related? (It happens on the previous build too)

**Comment by staticfloat** [comment]
Yeah, I'm not concerned about that.  Thanks as always.

**Pull request merged**
