### PR TITLE
Enable 0.3 and 0.4 on travis

### PR DESCRIPTION
**Pull request by yuyichao**

### CODE REVIEW

**Comment by yuyichao** [comment]
@staticfloat

**Comment by staticfloat** [comment]
Could you rebase this onto the `sf/breakageahoy` branch?

**Comment by yuyichao** [comment]
@staticfloat Seems that all the `Union`'s are gone so this only include Travis setting update now.

**Comment by staticfloat** [comment]
You need to change the base fork of this pull request to point to `sf/breakageahoy`.

**Comment by yuyichao** [comment]
I don't think I can change that so I just create a new one...

**Comment by staticfloat** [comment]
Thanks @yuyichao!

**Pull request closed without merging**
