### PR TITLE
add BSDPkg provider

### PR DESCRIPTION
**Pull request by iblis17**
cc @staticfloat

### CODE REVIEW

**Comment by iblis17** [comment]
ping @staticfloat ?

**Comment by staticfloat** [comment]
Where does `BSDPkg` come from?  Does it come from `BinDeps`?  Or from some other package?  If it's from `BinDeps`, I think we need to bump up the minimum version of BinDeps since it wasn't always defined.

**Comment by iblis17** [comment]
yes, it's from this PR:  https://github.com/JuliaLang/BinDeps.jl/pull/296

**Comment by iblis17** [comment]
hmm, BinDeps 0.6 requires Julia 0.5+

If I bump it, Julia 0.4 is still broken...

```patch
diff --git a/REQUIRE b/REQUIRE
index f00eb2d..6175631 100644
--- a/REQUIRE
+++ b/REQUIRE
@@ -1,5 +1,5 @@
 julia 0.4
-BinDeps
+BinDeps 0.6
 Compat 0.8.0
 @osx Homebrew
 @windows WinRPM
```

**Comment by staticfloat** [comment]
I've now changed this repository to use `BinaryProvider`, and it has FreeBSD packages available.  Please try it out and let me know if it all works!

**Pull request closed without merging**
